config/routes.rb
Rails.application.routes.draw do
  get 'calendriers/index'
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    delete 'users/destroy', to: 'users/registrations#destroy', as: :destroy_user_registration
  end

  root to: 'familles#index'

  # resources :items, only: [:edit, :update]
  resources :profils

  resources :familles do
    resources :items
  end

  resources :items do
    resources :profils
  end

  get '/regles', to: 'regles#show'
  get '/calendriers', to: 'calendriers#index'

  get '/weather/forecast', to: 'weather#forecast', defaults: { format: 'json' }

  # resources :items do
  #   resources :profils
  # end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/famille.rb
class Famille < ApplicationRecord
  validates :name, :info, presence: true
  has_many :items, dependent: :destroy
  belongs_to :user

  has_one_attached :photo_famille
end

app/controllers/familles_controller.rb
class FamillesController < ApplicationController
  before_action :set_famille, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index #permet de donner les droit de visualisation seulement sur index et show.


  def index
    @famille = Famille.new
    @familles = Famille.all.includes(:items)

    # Filtrer pour le type de Famille
    if params[:filter].present?
      famille_ids = params[:filter][:familles]

      # Vérifier si l'option "Toutes les familles" est cochée
      if params[:filter][:toutes_les_familles] == "1"
        # Si l'option est cochée, ignorer tout autre filtre de famille et afficher toutes les familles
        @familles = Famille.all.includes(:items)
      elsif famille_ids.present?
        @familles = @familles.where(id: famille_ids)
      end

      if params[:filter][:min_price].present? && params[:filter][:max_price].present?
        min_price = params[:filter][:min_price].to_f
        max_price = params[:filter][:max_price].to_f

        # Filtrer les familles en fonction du prix des articles
        @familles = @familles.joins(:items).where(items: { price: min_price..max_price })

        # Filtrer par taille minimale
        if params[:filter][:min_size].present?
          @familles = @familles.joins(:items).where("items.size >= ?", params[:filter][:min_size])
        end

        # Filtrer par taille maximale
        if params[:filter][:max_size].present?
          @familles = @familles.joins(:items).where("items.size <= ?", params[:filter][:max_size])
        end
      end
    end

  end




  def show
  end

  def new
    @famille = Famille.new
    authorize @famille
  end

  def create
    @famille = Famille.new(famille_params)
    @famille.user = current_user
    if @famille.save
      redirect_to familles_path(@famille)
      authorize @famille
    else
      render :new
    end
  end

  def edit
    @famille = Famille.find(params[:id])
    authorize @famille
  end

  def update
    @famille = Famille.find(params[:id])
    @famille.user = current_user
    @famille.update(famille_params)
    redirect_to familles_path
    authorize @famille
  end

  def destroy
    @famille = Famille.find(params[:id])
    @famille.destroy
    redirect_to familles_path
    authorize @famille
  end

  private

  def set_famille
    @famille = Famille.find(params[:id])
  end

  def famille_params
    params.require(:famille).permit(:name, :info, :user_id, :photo_famille)
  end
end

app/views/familles/edit.html.erb
<h1>Coucou</h1>

<%= form_for @famille do |f| %>

  <%= f.label :name, "Entre un nom" %>
  <%= f.text_field :name %>

  <%= f.label :info, "Entre les infos" %>
  <%= f.text_field :info %>

  <%= f.file_field :photo_famille %>

  <%= f.submit :Création, data: {confirm: "Valider les modifs"}  %>

<% end %>

<div class="bouton-add">
  <%= link_to'Retour', familles_path %>
</div>

app/views/familles/index.html.erb
<%# <div class="container"> %>
  <%# <div class="row mt-5"> %>
    <%# <div class="col-12 col-sm-8 col-md-4 offset-sm-2 offset-md-4"> %>
      <%# <div class="banner_homepage"> %>
      <%# </div> %>

        <div class="titre_index_items">
          <h1> <span>&#129305;</span> Trouve ta planche
            <% if user_signed_in? %>
                <%= current_user.nickname.capitalize %>
                <span>&#129305;</span>
              </p>
              <% else %>
              <span>&#129305;</span>
            <% end %>
          </h1>
        </div>

<!-- app/views/familles/index.html.erb -->
<%# <div id="temperature"></div> %>

  <div class="container-card-famille">

<!-- app/views/pages/index.html.erb -->


<%# ----------- Bouton User pour ajout de famille ----------- %>
  <%# <% if policy(Famille).create? %>
    <%# <div class="bouton-admin"> %>
    <%# <%= link_to 'Ajouter une Famille' , new_famille_path %>
    <%# </div> %>
  <%# <% end %>
<%# -----------Fin Bouton User pour ajout de famille ----------- %>


      <%# <%= link_to "Créer un nouvel item", new_famille_item_path(@famille), class: "btn btn-primary" %>

            <% @familles.each do |famille| %>
              <div class="card-famille-index">
<%# <%= link_to "Créer un nouvel item", new_famille_item_path(famille), class: "btn btn-primary" %>
                <div class= "img-index-famille">
                  <%= link_to famille_items_path(famille) do %>
                  <% if famille.photo_famille.attached? %>
                    <%= cl_image_tag famille.photo_famille.key, crop: :fill %>
                  <% else %>
                    <img class="img-item" src="https://res.cloudinary.com/dx8iv40ym/image/upload/v1661785315/pas_d_images_tritoq.png" alt="pas de photo">
                </div>
                  <% end %>
            <% end %>

                <div class="titre-index-famille">
                  <h2><%= famille.name.capitalize %></h2>
                </div>

<%# ----------- Bouton User pour Modiffier et Supprimer la famille ----------- %>
                <%# <div class="container-btn"> %>
                  <%# <% if famille.user == current_user %>
                    <%# <div class="bouton-user-famille"> %>
                      <%# <% if policy(famille).update? %>
                        <%# <td><%= link_to 'edite', edit_famille_path(famille) %></td>
                      <%# <% end %>
                    <%# </div> %>
                    <%# <% if policy(famille).destroy? %>
                      <%# <div class="bouton-user-famille"> %>
                        <%# <td><%= link_to 'supp', famille_path(famille), method: :delete, data: {confirm: "tu es sure?"} %></td>
                      <%# </div> %>
                    <%# <% end %>
                  <%# <% end %>
                <%# </div> %>
<%# ----------- Fin Bouton User pour Modiffier et Supprimer la famille----------- %>

          </div>
</div>

<%# ----------- Bouton Admin pour Modiffier et Supprimer la famille ----------- %>
              <%# <div> %>
                <%# <%= link_to 'Modifier', edit_famille_path(famille)%>
                <%# <%= link_to 'Supprimer', famille_path(famille), method: :delete, data: {confirm: "tu es sure?"} %>
              <%# </div> %>
<%# ----------- Fin Bouton Admin pour Modiffier et Supprimer la famille----------- %>

            <% end %>
            </div>
</div>
          </div>

  <div class="container">

  <div class="container_filtre_recommandation">
    <div class="container_filtre_index_familles">

    <div class="filtre_choix_famille_index_familles">
      <%= simple_form_for :filter, url: familles_path, method: :get do |f| %>
        <div class="form-check">
          <%= f.input :familles,
                      collection: Famille.all.map { |famille| [famille.name.capitalize, famille.id] },
                      as: :check_boxes %>
          <%= f.input :toutes_les_familles, as: :boolean, label: "Toutes les familles" %>
        </div>
    </div>

  <div class="filtre_choix_prix_index_familles">
    <div class="form-group">
      <%= f.label :min_price, "Prix minimum" %>
      <%= f.input :min_price, as: :numeric, input_html: { class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= f.label :max_price, "Prix maximum" %>
      <%= f.input :max_price, as: :numeric, input_html: { class: 'form-control' } %>
    </div>
  </div>

  <div class="filtre_choix_taille_index_familles">
      <!-- Champ de filtre pour la taille minimale -->
    <%= f.input :min_size, label: "Taille minimale" %>

    <!-- Champ de filtre pour la taille maximale -->
    <%= f.input :max_size, label: "Taille maximale" %>

<div class="container_btn_filtre_index_familles">
    <%= f.button :submit, "Filter", class: "btn_filtre_index_familles" %>
    <%# <%= link_to 'Réinitialiser' , familles_path , class: "btn_filtre_index_familles" %>
</div>
    <% end %>

  </div>
</div>

  <div class="container">

      <div class="container_recommandation_index_familles">
        <% @familles.each do |famille| %>
              <div class="titre_recommandation_index_familles">
          <h2><%= famille.name.capitalize %></h2>
      </div>

  <%# Trier les items du plus récent au plus ancien avant de les afficher %>
            <% famille.items.order(created_at: :desc).each do |item| %>
          <div class="card_recommandation_index_familles">
              <div class="img_card_recommandation_index_familles">
                <%= link_to famille_item_path(famille, item), class: "card-link" do %>
                <% if item.photo_1.attached? %>
                  <%= cl_image_tag item.photo_1.key, class:"card-item-img" %>
                <% else %>
                  <img class="img-item" src="https://res.cloudinary.com/dx8iv40ym/image/upload/v1661785315/pas_d_images_tritoq.png" alt="photo">
                <% end %>
              </div>
            <% end %>

            <div class="info_card_recommandation_index_familles">
              <h6><%= item.created_at.strftime("%d/%m/%Y") %></h6>
              <h6><%= item.name %></h6>
              <h6><%= item.taille %></h6>
              <h6><%= item.price %>€</h6>
            </div>
        </div>
            <% end %>
        <% end %>
      </div>
        </div>
</div>
          </div>

app/views/familles/new.html.erb
<h2>Ajoute la famille</h2>

<div class="card-new-famille">
  <ul style="list-style-type:none; padding-left:38%; margin-bottom:0px;">

    <%= form_for @famille do |f| %>

      <%= f.label :name, "Entre un nom" %>
      <%= f.text_field :name %>

      <%= f.label :info, "Entre les infos" %>
      <%= f.text_area :info %>

    <%= f.file_field :photo_famille, onchange: "previewImage(this);" %>

      <%= f.submit :Création %>

    <% end %>

<img id="photo-famille-preview" src="#" alt="Aperçu de l'image" style="display:none; max-width: 100%; max-height: 200px; border-radius: 10px" />

<script type="text/javascript">
  function previewImage(input) {
    var preview = document.getElementById('photo-famille-preview');
    preview.style.display = 'block';

    var reader = new FileReader();

    reader.onload = function (e) {
      preview.src = e.target.result;
    };

    reader.readAsDataURL(input.files[0]);
  }
</script>



  </ul>
</div>

  <div class="bouton-add">
    <%= link_to'Retour', familles_path %>
  </div>