config/routes.rb
Rails.application.routes.draw do
  get 'calendriers/index'
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    delete 'users/destroy', to: 'users/registrations#destroy', as: :destroy_user_registration
  end

  root to: 'familles#index'

  # resources :items, only: [:edit, :update]
  resources :profils

  resources :familles do
    resources :items
  end

  resources :items do
    resources :profils
  end

  get '/regles', to: 'regles#show'
  get '/calendriers', to: 'calendriers#index'

  get '/weather/forecast', to: 'weather#forecast', defaults: { format: 'json' }

  # resources :items do
  #   resources :profils
  # end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to familles_path, class: "navbar-brand" do %>
      <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpSYEtqi4r-UXJtSUODwTCUuALjZ_wujTrIQ&usqp=CAU" %>
    <% end %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <%# Ajout des liens supplémentaires à la navbar %>
          <div class="nav-item">
            <%= link_to "Les règles d'or", regles_path, class: "nav-link" %>
          </div>

          <div class="nav-item">
            <%= link_to "Calendrier", calendriers_path, class: "nav-link" %>
          </div>

          <div class="nav-item">
          <%= link_to "Vente", new_item_path, class: "nav-link" %>
        </li>

        <!-- Si vous êtes sur la page show d'une règle, affichez le bouton "Vends ta planche" -->
        <% if params[:controller] == "regles" && params[:action] == "show" %>
            <% if @familles.present? %>
              <% first_famille = @familles.first %>
              <%= link_to "Vends ta planche", new_famille_item_path(first_famille), class: "nav-link btn btn-primary"%>
            <% end %>
        <% end %>
          </div>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
      <li class="nav-item active">
<%= link_to "Vente", new_item_path, class: "nav-link" %>
</li>

          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <% if user_signed_in? && @profil.present? %>
              <% if @profil.img_profil.attached? %>
                <%= cl_image_tag(@profil.img_profil.key, class: "navbar_avatar rounded-circle", style: "object-fit: cover; width: 40px; height: 40px;", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
              <% else %>
                <%= image_tag("https://res.cloudinary.com/dx8iv40ym/image/upload/v1661785315/pas_d_images_tritoq.png", class: "profil_avatar rounded-circle", style: "object-fit: cover; width: 40px; height: 40px;", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
              <% end %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

  <% if current_user.profil.present? %>
    <%= link_to "Profil", profil_path(current_user.profil), class: "dropdown-item" %>
    <%= link_to "Modif ton Profil", edit_profil_path(current_user.profil), class: "dropdown-item" %>
  <% else %>
    <span class="dropdown-item disabled">Profil</span>
    <span class="dropdown-item disabled">Modif ton Profil</span>
  <% end %>
              <%= link_to "Modif tes paramètres", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
    </li>

<%# ----------- Bouton User pour ajout de famille ----------- %>
                      <%# <%= link_to "Modif tes paramètres", edit_user_registration_path, class: "dropdown-item" %>
                      <%# <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
<%# -----------Fin Bouton User pour ajout de famille ----------- %>

      </ul>
    </div>
  </div>
</div>