config/routes.rb
Rails.application.routes.draw do
  get 'calendriers/index'
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    delete 'users/destroy', to: 'users/registrations#destroy', as: :destroy_user_registration
  end

  root to: 'familles#index'

  # resources :items, only: [:edit, :update]
  resources :profils

  resources :familles do
    resources :items
  end

  resources :items do
    resources :profils
  end

  get '/regles', to: 'regles#show'
  get '/calendriers', to: 'calendriers#index'

  get '/weather/forecast', to: 'weather#forecast', defaults: { format: 'json' }

  # resources :items do
  #   resources :profils
  # end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/profil.rb
class Profil < ApplicationRecord
  validates :nom, :prenom, presence: true
  # belongs_to :item
  belongs_to :user

  has_one_attached :img_profil;


  before_validation :set_default_name

  validates :date_naissance, presence: true

  # information ajouté par default

  private

  def set_default_name
    self.nom = "info manquante" if nom.blank?
    self.prenom = "info manquante" if prenom.blank?
  end

end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController
  before_action :set_profil, only: [:show, :edit, :update, :destroy]

  def index
    @profils = Profil.all
    # @item = Item.find(params[:item_id])
  end

  def show
    @profil = current_user.profil
    authorize @profil

    @items = current_user.items

    @user = current_user
    # @item = current_user.items.find(params[:id]) # Ajoutez cette ligne pour récupérer l'item associé
  end

  def new
    @profil = Profil.new
    authorize @profil
  end

  def create
    @profil = Profil.new(profil_params)
    authorize @profil

    @profil.user = current_user
    if @profil.save
      redirect_to profil_path(@profil)
    else
      render :new
      puts @profil.errors.full_messages
    end
  end


  def edit
    @profil = Profil.find(params[:id])
    authorize @profil
  end

  def update
    @profil = Profil.find(params[:id])
    authorize @profil

    @profil.user = current_user
    @profil.update(profil_params)
    redirect_to profil_path
  end

  def destroy
    @profil = Profil.find(params[:id])
    authorize @profil

    @profil.destroy
    redirect_to profils_path
  end

  private

  def set_item

  end

  def set_profil
    if params[:id].present?
      @profil = Profil.find(params[:id])
    else
      @profil = Profil.new
    end
    # @profil = Profil.find(params[:id])
    # redirect_to root_path, alert: "Profil non trouvé" unless @profil
  end

  def profil_params
    params.require(:profil).permit(:nom, :prenom, :img_profil, :date_naissance)
  end


end

app/views/profils/edit.html.erb
<div class="container">

  <div class= "titre_edit_profil">
    <h1>Modification de ton profil</h1>
  </div>

  <div class="container_edit_profil">

<div class="edit_profil_img">
  <%= form_for @profil do |f| %>

    <!-- Champ de fichier pour l'image du profil -->
    <%= f.file_field :img_profil, id: "img_profil_input", onchange: "previewImage(this);" %>

    <!-- Image actuelle de l'avatar du profil -->
    <% if @profil.img_profil.attached? %>
      <%= image_tag @profil.img_profil, class: "avatar_edit_profil", id: "photo-famille-preview", style: "display: block;" %>
    <% else %>
      <img id="photo-famille-preview" class="avatar_edit_profil" src="url_de_l_image_par_defaut" alt="Image par défaut" style="display: none;" />
    <% end %>

    <!-- Script JavaScript pour afficher l'aperçu de l'image -->
    <script type="text/javascript">
      function previewImage(input) {
        var preview = document.getElementById('photo-famille-preview');
        preview.style.display = 'block';

        var reader = new FileReader();

        reader.onload = function (e) {
          preview.src = e.target.result;
        };

        reader.readAsDataURL(input.files[0]);
      }
    </script>
  </div>


    <div class="edit_profil_info">
      <%= f.label :nom, "Entre ton nom" %>
      <%= f.text_field :nom %>

      <%= f.label :prenom, "Entre ton prenoms" %>
      <%= f.text_field :prenom %>

        <%= f.label :date_naissance, "Date de naissance" %>
      <div class="container_date_naissance">
        <%= f.date_select :date_naissance, {  order: [:day, :month, :year], start_year: Date.current.year - 100, end_year: Date.current.year, use_month_numbers: true }, { class: "form-control" } %>
      </div>
      <%= f.submit :Création %>
      <% end %>
    </div>
  </div>


</div>

app/views/profils/index.html.erb
<h1>Bonjour c'est l'index des profils
  <%= current_user.nickname.capitalize %>
  <%= current_user.email %>
  <%= current_user.password %>

<% @profils.each do |profil| %>
  <div>
    <!-- Autres informations du profil -->

    <% if profil.user && profil.user.img_user.attached? %>
      <%= cl_image_tag profil.user.img_user.key, class: "profil-img" %>
    <% else %>
      <img class="img-item" src="https://res.cloudinary.com/dx8iv40ym/image/upload/v1661785315/pas_d_images_tritoq.png" alt="photo">
    <% end %>
  </div>
<% end %>
      <%# <%= image_tag profil.user.img_user, class: "profil-img" %> %>
</h1>

  <% @profils.each do |profil| %>
          <ul>

            <h2><%= profil.nom %></h2>
            <h2><%= profil.prenom %></h2>
            <h2><%= profil.email %></h2>

          </ul>

          <%= link_to "Ton profil", profil_path(profil) %>
          <%= link_to "Modifie ton profil", edit_profil_path(profil) %>

          <td><%= link_to 'supprime ton profil', profil_path(profil), method: :delete, data: {confirm: "tu es sure?"} %></td>

  <% end %>

<div class="bouton-admin">
  <%= link_to "Retouche ton profil", new_profil_path %>
</div>

app/views/profils/new.html.erb
<div class="container">

  <div class= "titre_edit_profil">
    <h1>Création de ton profil</h1>
  </div>

  <div class="container_edit_profil">

<div class="edit_profil_img">
  <%= form_for @profil do |f| %>

    <!-- Champ de fichier pour l'image du profil -->
<%= f.file_field :img_profil, id: "img_profil_input", onchange: "previewImage(this);", placeholder: "Ajoute ta photo" %>


    <!-- Image actuelle de l'avatar du profil -->
    <% if @profil.img_profil.attached? %>
      <%= image_tag @profil.img_profil, class: "avatar_edit_profil", id: "photo-famille-preview", style: "display: block;" %>
    <% else %>
      <img id="photo-famille-preview" class="avatar_edit_profil" src="url_de_l_image_par_defaut" alt="Image par défaut" style="display: none;" />
    <% end %>

    <!-- Script JavaScript pour afficher l'aperçu de l'image -->
    <script type="text/javascript">
      function previewImage(input) {
        var preview = document.getElementById('photo-famille-preview');
        preview.style.display = 'block';

        var reader = new FileReader();

        reader.onload = function (e) {
          preview.src = e.target.result;
        };

        reader.readAsDataURL(input.files[0]);
      }
    </script>
  </div>


    <div class="edit_profil_info">
      <%= f.label :nom, "Entre ton nom" %>
      <%= f.text_field :nom %>

      <%= f.label :prenom, "Entre ton prenoms" %>
      <%= f.text_field :prenom %>

        <%= f.label :date_naissance, "Date de naissance" %>
      <div class="container_date_naissance">
        <%= f.date_select :date_naissance, {  order: [:day, :month, :year], start_year: Date.current.year - 100, end_year: Date.current.year, use_month_numbers: true }, { class: "form-control" } %>
      </div>
      <%= f.submit :Création %>
      <% end %>
    </div>
  </div>


</div>

app/views/profils/show.html.erb
  <%# <div class="bouton-add">
    <%= link_to'Home', familles_path %>
  <%# </div> %>

<div class="container">

  <div class= "titre_show_profil">
    <h1>Ton Profil</h1>
  </div>

  <div class="profil_user">
    <div class="profil_info_user">
      <ul>
        <% if user_signed_in? && @profil.present? %>
          <% if @profil.img_profil.attached? %>
            <%= cl_image_tag(@profil.img_profil.key, class: "profil_avatar rounded-circle", style: "object-fit: cover; width: 200px; height: 200px;", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <% else %>
            <%= image_tag("https://res.cloudinary.com/dx8iv40ym/image/upload/v1661785315/pas_d_images_tritoq.png", class: "profil_avatar rounded-circle", style: "object-fit: cover; width: 200px; height: 200px;", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <% end %>
        <% end %>

      <h6>Pseudo :</h6> <h2><%= @user.nickname %></h2>
      <h6><h6><h6>Email : </h6><h2><%= @user.email %></h2>
    </div>
    <div class="profil_info_profil">
      <h6>Nom : </h6><h2><%= @profil.nom.capitalize %></h2>
      <h6>Prenom :</h6> <h2><%= @profil.prenom.capitalize %></h2>
      <h6>Date de naissance :</h6><h2> <%= @profil.date_naissance.strftime('%d/%m/%Y') %></h2>
      <h6>Date de création du profil :</h6><h2><%= @profil.created_at.strftime("%d/%m/%Y") %></h2>
      </ul>
    </div>
  </div>

<h1>Mes Planches en Vente</h1>
<div class="profil_items">
  <% if @items.any? %>

    <% @items.order(created_at: :desc).each do |item| %>
      <div class="card_profil_items">
        <div class="container_img_info_card_show_profil">
          <div class="img_card_show_profil">
                          <%= link_to famille_item_path(item.famille_id, item), class: "card-link" do %>
          <% if item.photo_1.attached? %>
            <%= image_tag item.photo_1, class: "card-item-img" %>
          <% else %>
            <img class="img_profil_item" src="https://res.cloudinary.com/dx8iv40ym/image/upload/v1661785315/pas_d_images_tritoq.png" alt="pas de photo">
          <% end %>
                      <% end %>

          </div>

          <div class="info_card_show_profil">
            <h5><%= item.marque.capitalize %></h5>
            <h6><%= item.price %>€</h6>
            <h6><%= item.taille %></h6>
        <p><%= item.created_at.strftime("%d/%m/%Y") %></p>
          </div>
        <div class="btn_card_profil_items">
          <%# <%= button_to 'Apercu', famille_item_path(item.famille_id, item) %>
          <%# <%= button_to'Modifier', edit_item_path(item) %>
          <%= button_to "Modifier", edit_item_path(item), method: :get %>

          <%# <%= button_to 'Modifier', edit_famille_item_path(item.famille_id, item) %>
          <%= button_to "Supprimer", item_path(item), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cet item ?" } %>
        </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>Aucune planche mise en vente</p>
  <% end %>
</div>



  </div>
</div>
</div>